import {
  themes,
  fontFamily,
  fontWeights,
  layout,
  motion,
  radius,
  spacing,
  typeScale,
  type FontRole,
  type ThemeColors,
} from './index';

const kebab = (s: string) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

const colorVars = (c: ThemeColors) =>
  Object.entries(c).map(([k, v]) => `--color-${kebab(k)}: ${v};`);

/**
 * Renders all tokens as CSS custom properties: dark theme on :root,
 * light theme colors under [data-theme="light"] (same variable names).
 */
export function toCssVariables(): string {
  const lines: string[] = ['color-scheme: dark;', ...colorVars(themes.dark)];
  const lightLines = ['color-scheme: light;', ...colorVars(themes.light)];
  lines.push(`--font-display: '${fontFamily.display}', Georgia, serif;`);
  lines.push(`--font-ui: '${fontFamily.ui}', system-ui, sans-serif;`);
  for (const [k, v] of Object.entries(typeScale)) {
    lines.push(`--text-${k}-font: var(--font-${v.font});`);
    lines.push(`--text-${k}-weight: ${v.weight};`);
    lines.push(`--text-${k}-size: ${v.fontSize}px;`);
    lines.push(`--text-${k}-line: ${v.lineHeight}px;`);
  }
  for (const [k, v] of Object.entries(spacing)) lines.push(`--space-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(radius)) lines.push(`--radius-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(layout)) {
    lines.push(`--layout-${kebab(k)}: ${k === 'tabBarBgOpacity' ? v : `${v}px`};`);
  }
  lines.push(`--motion-duration: ${motion.durationMs}ms;`);
  lines.push(`--motion-easing: ${motion.easing};`);

  const textClasses = Object.keys(typeScale).map(
    (k) =>
      `.text-${k} {\n  font-family: var(--text-${k}-font);\n  font-weight: var(--text-${k}-weight);\n` +
      `  font-size: var(--text-${k}-size);\n  line-height: var(--text-${k}-line);\n}`,
  );

  const block = (selector: string, decls: string[]) =>
    `${selector} {\n${decls.map((l) => `  ${l}`).join('\n')}\n}`;

  return `/* Generated by packages/tokens/scripts/build-css.ts. Do not edit. */\n${block(':root', lines)}\n\n${block('[data-theme="light"]', lightLines)}\n\n@media (prefers-reduced-motion: reduce) {\n  :root {\n    --motion-duration: 0ms;\n  }\n}\n\n${textClasses.join('\n\n')}\n`;
}

/** Subsets to self-host. Mongolian Ө/Ү are only in cyrillic-ext, never drop it. */
export const webFontSubsets = ['latin', 'cyrillic', 'cyrillic-ext'] as const;

/**
 * Builds @font-face rules from Fontsource's per-weight CSS, keeping only webFontSubsets
 * (with their unicode-range, so browsers download a subset only when it is used).
 * URLs become package paths that the consuming Vite app resolves and bundles.
 */
export function toFontFaceCss(readFontsourceCss: (pkg: string, weight: number) => string): string {
  const blocks: string[] = [];
  for (const role of Object.keys(fontFamily) as FontRole[]) {
    const pkg = `@fontsource/${fontFamily[role].toLowerCase()}`;
    for (const weight of fontWeights[role]) {
      const css = readFontsourceCss(pkg, weight);
      for (const subset of webFontSubsets) {
        const marker = `/* ${fontFamily[role].toLowerCase()}-${subset}-${weight}-normal */`;
        const start = css.indexOf(marker);
        if (start === -1) throw new Error(`${pkg} ${weight}: subset ${subset} not found`);
        const end = css.indexOf('}', start) + 1;
        const block = css.slice(start, end).replaceAll('url(./files/', `url(${pkg}/files/`);
        if (!block.includes('unicode-range')) throw new Error(`${marker} has no unicode-range`);
        blocks.push(block);
      }
    }
  }
  return `/* Generated by packages/tokens/scripts/build-css.ts. Do not edit. */\n${blocks.join('\n\n')}\n`;
}
