import { colors, fontFamily, layout, motion, radius, spacing, typeScale } from './index';

const kebab = (s: string) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

/** Renders all tokens as CSS custom properties on :root. */
export function toCssVariables(): string {
  const lines: string[] = [];
  for (const [k, v] of Object.entries(colors)) lines.push(`--color-${kebab(k)}: ${v};`);
  lines.push(`--font-display: '${fontFamily.display}', Georgia, serif;`);
  lines.push(`--font-ui: '${fontFamily.ui}', system-ui, sans-serif;`);
  for (const [k, v] of Object.entries(typeScale)) {
    lines.push(`--text-${k}-size: ${v.fontSize}px;`);
    lines.push(`--text-${k}-line: ${v.lineHeight}px;`);
  }
  for (const [k, v] of Object.entries(spacing)) lines.push(`--space-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(radius)) lines.push(`--radius-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(layout)) {
    lines.push(`--layout-${kebab(k)}: ${k === 'tabBarBgOpacity' ? v : `${v}px`};`);
  }
  lines.push(`--motion-duration: ${motion.durationMs}ms;`);
  lines.push(`--motion-easing: ${motion.easing};`);
  return `/* Generated by packages/tokens/scripts/build-css.ts. Do not edit. */\n:root {\n${lines
    .map((l) => `  ${l}`)
    .join(
      '\n',
    )}\n}\n\n@media (prefers-reduced-motion: reduce) {\n  :root {\n    --motion-duration: 0ms;\n  }\n}\n`;
}
